account/urls.py
from . import views
from django.urls import path

# create a name space
app_name = 'account'


urlpatterns = [
    path("account/signup",views.resgisterView,name='signup'),
    path("<pk>/update",views.UserEditView.as_view(),name='edit_profile'),
]

blog/urls.py
from django import views
from django.urls import path
from .views import contactView, displayTime, loginView, profileView, logoutView, aboutView
from ecommerce.views import Myviews
from blog.views import book_list, post_list, post_detail

#create a name space
app_name = 'blog'


urlpatterns = [
    path("books_list/",book_list),
    path("",post_list),
    path("contact/",contactView, name='contact'),
    path("about/",aboutView,name ='about'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', post_detail, name='post_detail'),
    path("login/",loginView,name='login'),
    path("profile/",profileView,name='profile'),
    path("logout/",logoutView,name='logout'),
    

]

ecommerce/urls.py
import imp
from django.urls import path
from .views import productView
from ecommerce.views import Myviews 

urlpatterns = [
    path("",productView),
    path('about/',Myviews.as_view())
]

introtodjango/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("blog.urls")),
    path("ecommerce/",include("ecommerce.urls")),
    path("account/",include("account.urls")),

    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account/models.py
from django.db import models

# Create your models here.

blog/models.py
import email
from turtle import title
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class Book(models.Model):
    title = models.CharField(max_length=255)
    subtitle = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    isbn = models.CharField(max_length=13)

    def __str__(self):
        return self.title


# Blog Model 
class Post(models.Model):
    STATUS_CHOICES = (
        ('draft','Draft'),
        ('published','Published')
        )
    title = models.CharField(max_length=250)
    post_image = models.ImageField(blank = True, null = True)
    slug = models.CharField(max_length=250,unique_for_date='publish')
    author = models.ForeignKey(User,on_delete=models.CASCADE,related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated =models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES,default='draft')
    class Meta:
        ordering = ('-publish',)
    def __str__(self):
        return self.title 

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,self.publish.month,self.publish.day, self.slug])




class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=255)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'
    

account/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


# Create user form as a class

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email','body')

account/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib import messages
from .forms import CreateUserForm

from django.views.generic import UpdateView
from django.contrib.auth.forms import UserChangeForm
from django.urls import reverse_lazy
from django.contrib.auth.models import User

# Create your views here.
def resgisterView(request):
    form = CreateUserForm()
    if request.method == "POST":
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password, email=email)
            login(request, user)
            messages.success(request, 'Account created successfully')
            return redirect('blog:profile')
    else:
        form = CreateUserForm()
    return render(request,'Registration/signup.html',{'form':form})

class UserEditView(UpdateView):
    model = User
    form_class = UserChangeForm
    template_name = 'Registration/editprofile.html'
    success_url = reverse_lazy('blog:profile')

blog/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
import datetime
from django.views.generic import TemplateView
from .models import Book , Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import CommentForm
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def displayTime(request):
    now = datetime.datetime.now()
    html = "time is {}".format(now)
    return HttpResponse(html)

# def homeView(request):
#     return render(request, 'base.html', {})

def contactView(request):
    return render(request, 'contact.html', {})


def aboutView(request):
    return render(request, 'about.html', {})


def book_list(request):
    books = Book.objects.all()
    return render(request,"book_list.html",{'books':books})



#view for all posts
def post_list(request):
    posts = Post.objects.all()
    paginator = Paginator(posts,2)
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)

    except PageNotAnInteger:
       posts = paginator.page(1)
    
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)


    return render(request, "index.html", {'page':page,'posts':posts})

#view for single post 
def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month, publish__day=day)
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method== 'POST':
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.post = post
            new_comment.save()
    else:
        comment_form = CommentForm() 
    return render(request, 'post_detail.html',{'post':post,'comments':comments,'new_comment':new_comment,'comment_form':comment_form})

def loginView(request):
    if request.method == 'POST':
        form = AuthenticationForm(request,data=request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                messages.info(request, f"You are now logged in as {username}.")
                return redirect("blog:profile")
            else:
                messages.error(request, f"Invalid username or password")
        else:
            messages.error(request, f"Invalid username or password")
    form = AuthenticationForm()            
    return render(request,'authenticate/login.html',{'form':form})



@login_required(login_url='blog:login')
def profileView(request):
    return render(request,"profile.html",{})

def logoutView(request):
    logout(request)
    return redirect('/')

ecommerce/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import View

# Create your views here.
def productView(request):
    html = "Welcome to my product page"
    return HttpResponse(html)

# Class based views.
class Myviews(View):
    def get(self,request):
        return HttpResponse("<h1>This is class based view</h1>")

blog/templates/about.html
{% extends "base.html" %}

{% block content %}

{% endblock %}

blog/templates/authenticate/login.html
{% extends "base.html" %}
{% block content %}

{% load crispy_forms_tags %}

<div class="login_wrapper">
    <div class="container">
        <!-- Login -->
        <h2>Log In</h2>
        <form method="POST" class="form">
            {% csrf_token %}
            {{ form |crispy }}
            <button type="submit">Log In</button>
            <p class="text-center">Don't have an account? <a href="{% url 'account:signup' %}">Create an account</a></p>
        </form>
    </div>
</div>
{% endblock %}

blog/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"> 
    <link rel="stylesheet" href="{% static 'css/app.css' %}">
    <link rel="stylesheet" href="{% static 'css/mobile.css'%}">
    

</head>
<body>
    <nav>
        <div class="logo">
            <h1>Fashion Blog</h1>
        </div>
        <ul class="nav-links">
            <li><a href="#">Home</a></li>
            <li><a href="{% url 'blog:about' %}">About</a></li>
            <li><a href="{% url 'blog:contact' %}">Contact</a></li>
            <li><a href="#">Blog</a></li>
            {% if user.is_authenticated %}
            <li><a href="{% url 'blog:logout' %}">Logout</a></li>
            {% else %}
            <li class="nav-item"><a href="{% url 'blog:login' %}" class="nav-link">Login</a></li>
            <li><a href="{% url 'account:signup' %}">Sign Up</a></li>
            {% endif %}

            {% if request.user.is_authenticated %}
            <li>Hello {{request.user}}</li>
            {% endif %}
        </ul>
        <div class="burger">
            <div class="line1"></div>
            <div class="line2"></div>
            <div class="line3"></div>
        </div>
    </nav>
    <div class="container mt-5">
        {% if message %}
            {% for message in messages %}
            <div class="alert alert-danger mt-5" role="alert">
                {{message}}
            </div>
            {% endfor %}
        {% endif %}
    </div>
    {% block content %}

    {% endblock content %}
    
</body>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.min.js" integrity="sha384-IDwe1+LCz02ROU9k972gdyvl+AESN10+x7tBKgc9I5HFtuNz0wWnPclzo6p9vxnk" crossorigin="anonymous"></script>
<script src="{% static 'js/app.js' %}"></script> 
</html>

blog/templates/book_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Book List</title>
</head>
<body>
    <h1>This Is My Book List</h1>
    {%for book in books%}
    <ul>
        <li>Title: {{book.title}}</li>
        <li>Subtitle: {{book.subtitle}}</li>
        <li>Author: {{book.author}}</li>
        <li>ISBN: {{book.isbn}}</li>


    </ul>
    {%endfor%}
</body>
</html>

blog/templates/contact.html
{% extends "base.html" %}

{% block content %}

    
        <div class="contact">
        <h6>CONTACT ME</h6>
        
        <div class="info">
            <i class="fa fa-user"></i>
            <input type="text" id="info" placeholder="First Name">
        </div>
       
        <div class="info">
            <i class="fa fa-user"></i>
            <input type="text" id="info" placeholder="Last Name">
        </div>

        <div class="info">
            <i class="fa fa-envelope-o"></i>
            <input type="text" id="info" placeholder="Email">
        </div>

        <div class="info">
            <i class="fa fa-pencil"></i>
            <input type="text" id="info" placeholder="Message">
        </div>
        
        <div class="info">
            <i class="fa fa-phone"></i>
            <input type="text" id="info" placeholder="Phone">
        </div>

        <button type="submit" class="send" id="submit">Send</button>
    </div>

{% endblock %}    

blog/templates/index.html
{% extends "base.html" %}
{% block content %}

    {% load static %}

    <img src="{% static 'images/music-production-equipment.jpg' %}" alt="My Image">
    <h1>This Is My Post List</h1>
    {% for post in posts %}
        <h1>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>    
        </h1>
        {% if post.post_image %}
        <img src="{{ post.post_image.url }}" alt="">
        {% endif %}
        
        <p class="date">
        Published {{ post.publish }} by {{ post.author }}
        </p>

        {{ post.body|truncatewords:30|linebreaks }}
        
{% endfor %}

{% include "pagination.html" with page=posts %}

{% endblock %}

blog/templates/pagination.html
<div class="pagination container justify-content-center">
    <ul class="pagination">
        <li class="page-item">
            {% if page.has_previous %}
               <a href="?page={{ page.previous_page_number}}" class="page-link">
                   Previous
                </a>
            {% endif %}    
        </li>

        <li class="page-item page-link">
            page{{ page.number }} 
        </li>
        <li class="page-item page-link"> of </li> 

        <li class="page-item page-link">{{ page.paginator.num_pages }}</li>    

        <li class="page-item">
        {% if page.has_next %}
               <a href="?page={{ page.next_page_number}}" class="page-link">
                Next
               </a>
         {% endif %}    
        </li>
    </ul>

</div>

blog/templates/post_detail.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}

    <h1>{{ post.title }}</h1>
    {% if post.post_image %}
    <img src="{{ post.post_image.url }}" alt="">
    {% endif %}
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|linebreaks }}

    <!-- comment section -->
<div class="container">
    {% with comments.count as total_comments %}
    <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
    </h2>
{% endwith %}

{% for comment in comments %}
    <div class="comment">
        <p class="info">
            Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}
        </p>
        
        {{ comment.body|linebreaks }}
    
    </div>
    
    {% empty %}

    <p>
        There are no comments yet!!
    </p>

{% endfor %}

{% if new_comment %}
    <h2>
        Your comment has been added
    </h2>
{% else %}
    <h2>
        Add a new comment
    </h2>
    <form method="POST">
        {{ comment_form|crispy }}
        {% csrf_token %}
        <p><input type="submit" value="Add comment"></p>
    </form>
{% endif %}
</div>

{% endblock %}

blog/templates/profile.html
{% extends "base.html" %}

{% block content %}
<a href="{% url 'account:edit_profile' user.id %}">Edit your profile</a>
{% endblock %}